### ISSUE TITLE
Application dependencies?

### ISSUE THREAD

**Issue by siolag161** [burke-software/schooldriver#222]
Hi, first of all thank you for open sourcing this great product.

Actually it's not a issue per ser, i would like to ask how one can use not all but only some of the apps. Indeed, I am now trying to help out my alma mater high school and build a alumni database. Therefore, makes sense to use only use `alumni` and other relevant apps but not `discipline` and `courses`.

What is the best way to achieve this? I have been trying to cancel out the apps in the settings.py but apparently it's not that simple due to complex dependencies. 

Thanks in advance

**Comment by bufke** [comment]
This isn't really supported but might be possible. You might consider

- Build a new project and use this as a model and ideas for it
- Greatly refactor the apps here so they can be run more independently and note a clear dependencies chain (like most apps would require the sis module)
- Use the application as is and adjust the templates or permissions to hide things you don't want. This may be the quickest approach

We aren't doing any active development right now - but I am talking with some schools about future funding. If you think you can make some contributions to the project I could volunteer to help - but my time is very limited. Might have more time later in the year.
